name: Package

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ref:
        description: "Enter a tag or commit to package"
        default: ""

jobs:
  windows_package:
    runs-on: windows-2019
    strategy:
      matrix:
        arch: [x64, x86]
        python: ["3.10"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python}}
          architecture: ${{ matrix.arch }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: '%LOCALAPPDATA%\pip\Cache'
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('tox.ini', 'setup.py', 'requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Prepare pip
        run: python -m pip install --upgrade pip wheel

      - name: Install Python dependencies
        run: >
          python -m pip install
          pyinstaller
          ifaddr

      - name: Freeze Deluge
        run: |
          pyinstaller --clean --distpath freeze --log-level DEBUG listinterface.py

      - uses: actions/upload-artifact@v2
        with:
          name: listinterface-py${{ matrix.python }}-${{ matrix.arch }}
          path: freeze/*.exe
